source :rubygems

# Ruby on Rails 3
gem 'rails', '~> 3.1.0'

# DBMS
gem 'sqlite3'
gem 'pg', :require => 'pg', :group => [:production]

# Asset template engines
gem 'sass-rails', '~> 3.1.0'
gem 'coffee-script'
gem 'uglifier'

# JS
gem 'jquery-rails'
gem 'execjs'
gem 'therubyracer'

# Internationalization
gem 'gettext_i18n_rails'
gem "fast_gettext", '~> 0.6.1'
gem "gettext", '>= 1.9.3', :require => false

# Others
gem 'redcarpet'
gem 'gmaps4rails'
gem 'bcrypt-ruby'
gem 'omniauth'

# Some TDD candy
gem "rspec-rails", :group => [:test, :development]
gem 'jasmine', :group => [:test, :development]
group :test do
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'guard-rspec'
  gem 'guard-spork'
  gem 'guard-coffeescript'
  gem 'libnotify'
  gem 'spork', '> 0.9.0.rc'
  gem 'libxml-ruby'
end


