source 'http://rubygems.org'

# Ruby on Rails v3.1.0
gem 'rails', '3.1.0'

# DBMS
gem 'sqlite3'
gem 'pg', :require => 'pg', :group => [:production]

# Asset template engines
gem 'sass-rails', '~> 3.1.0'
gem 'coffee-script'
gem 'uglifier'

# JS
gem 'jquery-rails'
gem 'execjs'
gem 'therubyracer'

# Internationalization
gem 'gettext_i18n_rails'
gem "fast_gettext", '>= 0.5'
gem "gettext", '>= 1.9.3', :require => false

# Others
gem 'redcarpet'


# Some gems available only in development and test environments
group :development, :test do
  gem 'nifty-generators'
  gem 'jasmine'
  gem 'rspec-rails'
  gem 'turn', :require => false
end

# Some test-exclusive gems
group :test do
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'guard-rspec'
  gem 'libnotify'
  gem 'rb-inotify'
  gem 'database_cleaner'
  gem 'spork', '> 0.9.0.rc'
  gem 'guard-spork'
end


